[project]
name = "a2ui-ucp-business-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk>=0.3.0",
    "click>=8.1.8",
    "google-adk>=1.8.0",
    "google-genai>=1.27.0",
    "python-dotenv>=1.1.0",
    "litellm",
    "a2ui",
    "jsonschema>=4.0.0",
    "ucp-sdk>=0.1.0",
    "httpx>=0.28.1",
    "uvicorn>=0.35.0",
    "json-repair>=0.57.1",
]


[tool.uv.sources]
a2ui = { path = "a2ui_extension" }
